definitions:
  services:
    docker:
      memory: 7128
image:
  name: 957685875802.dkr.ecr.eu-central-1.amazonaws.com/bitbucket-builder:latest
  aws:
    access-key: $AWS_ACCESS_KEY_ID
    secret-key: $AWS_SECRET_ACCESS_KEY
clone:
  depth: 1
pipelines:
  branches:
    master:
      - step:
          size: 2x
          services:
            - docker
          caches:
            - docker
            - node
            - composer
          name: build
          deployment: production
          script:
            - BUCKET="getportal-landing"
            - yarn install
            - yarn build
            - pipe: atlassian/aws-s3-deploy:0.4.5
              variables:
                S3_BUCKET: $BUCKET
                LOCAL_PATH: "build"
                ACL: "public-read"
                CACHE_CONTROL: "max-age=3600"
            - aws s3 cp s3://$BUCKET/index.html s3://$BUCKET/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
