export const tuttiTeamData = [
  {
    id: 1,
    name: "Sandra",
    cognome: "Sabia",
    mansione: "Ux Designer",
    team: "Designer",
    contratto: "Full",
    scadenza: "Indeterminato",
    busta_paga_luglio: "Inoltrata",
  },
  {
    id: 2,
    name: "Enrico",
    cognome: "Sella",
    mansione: "Full Stack",
    team: "Developers",
    contratto: "Full",
    scadenza: "Indeterminato",
    busta_paga_luglio: "Inoltrata",
  },
  {
    id: 3,
    name: "Marco",
    cognome: "Bianchi",
    mansione: "Sales",
    team: "Venditori",
    contratto: "Stage",
    scadenza: "2/09/22",
    busta_paga_luglio: "da inoltrare",
  },
  {
    id: 4,
    name: "Felice",
    cognome: "Castelli",
    mansione: "",
    team: "",
    contratto: "Determinato",
    scadenza: "20 /07/22",
    busta_paga_luglio: "da inoltrare",
  },
];
